install.packages("collapse")
install.packages("data.table")
install.packages("dplyr")
install.packages("exactextractr")
install.packages("gfcanalysis")
install.packages("ggmap")
install.packages("landscapemetrics")
install.packages("landscapetools")
install.packages("osmdata")
install.packages("osmextract")
install.packages("purrr")
install.packages("readxl")
install.packages("remotes")
remotes::install_github("statnmap/cartomisc")
install.packages("terra")
install.packages("wdpar")
# install.packages("lwgeom")
