install.packages("dplyr")
install.packages("exactextractr")
install.packages("landscapemetrics")
install.packages("landscapetools")
install.packages("osmdata")
install.packages("remotes")
remotes::install_github("statnmap/cartomisc")
install.packages("terra")

# install.packages("lwgeom")
